### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by Monk9636** [svenkreiss/socialforce#3]
I cloned the source into my computer several days ago, and use cmd to the file directory and run the instruction "pip install 'socialforce[test,plot]'" and "pip install -e '.[test,plot]'", both return error. First command said "ERROR: Could not find a version that satisfies the requirement socialforce[plot,test] (from versions: none);ERROR: No matching distribution found for socialforce[plot,test]", Second command said "Obtaining file:///F:/GA/socialforce
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\shu\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'F:\\GA\\socialforce\\setup.py'"'"'; __file__='"'"'F:\\GA\\socialforce\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Shu\AppData\Local\Temp\pip-pip-egg-info-9y13w3ed'
         cwd: F:\GA\socialforce\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "F:\GA\socialforce\setup.py", line 17, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 312: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. ".by the way, my operation system is windows 10, and my pip version is ‘pip 20.1.1’.Thanks

**Comment by Monk9636** [comment]
and my python version is Python 3.8.2. Seen from the second error, i suppose that some code format problem are the reason

**Comment by svenkreiss** [comment]
The error message points to a problem in parsing the readme. 
Because the authors of the original Social Force paper have utf8 characters in their name, Windows seems to have a problem parsing those.

Try prepending your install command with `PYTHONIOENCODING=utf8` to have:
`PYTHONIOENCODING=utf8 pip install -e '.[test,plot]'`

**Comment by svenkreiss** [comment]
Or if you are installing a local copy, change the unicode characters in the readme in Peter Molnar's name.

**Comment by Monk9636** [comment]
thanks a lot! I changed the "    long_description=open('README.rst'').read()," into "    long_description=open('README.rst',encoding='utf-8').read()," in line 17 of setup.py. and it installed successfully, but when I run pytest instruction, all test goes no error except the second one named "scenarios_pedpedspace".Is that normal?

**Comment by Monk9636** [comment]
errors are same and says "TypeError: 'MovieWriterRegistry' object is not an iterator"

**Comment by Monk9636** [comment]
hi, I googled a lot and it seems error comes from the Matplotlib's animation known bug. which is say, must change the save the gif in another way? but I am first to use Matplotlib package, so is there another way to save the simulation gif?

**Comment by Monk9636** [comment]
I just figure it out . it is because i didn't install 'imagemagick' and 'pythonmagick', the test goes no error after i installed them. i gona close this issue and thanks anyway! best wishes!
